![imagen](./img/ejercicios.png)

In [82]:
import numpy as np

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [84]:
my_array = np.arange(0, 10)
print(my_array)

[0 1 2 3 4 5 6 7 8 9]


In [85]:
my_array[::-2]

array([9, 7, 5, 3, 1])

In [92]:
my_array[my_array %2!=0][::-1]

array([9, 7, 5, 3, 1])

## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [98]:
my_array[-2:-4:-1]

array([8, 7])

## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [99]:
my_array[2::-1]

array([2, 1, 0])

## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [100]:
ej_4 = np.arange(1, 21).reshape(4, 5)
print(ej_4)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [102]:
ej_4 = ej_4[::-1, ::-1]

In [103]:
print(ej_4)

[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [105]:
ej_4[-1:-3:-1, -1:-3:-1]

array([[1, 2],
       [6, 7]])

## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [106]:
ej_4

array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

In [107]:
ej_4[-1::-2, -1::-2]

array([[ 1,  3,  5],
       [11, 13, 15]])

## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [112]:
ej_4

array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

In [118]:
ej_4[:0:-1]

array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])

## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [126]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])

In [128]:
x[np.array(x == "Loro")]

array(['Loro', 'Loro'], dtype='<U5')

In [129]:
x[x == "Loro"]

array(['Loro', 'Loro'], dtype='<U5')

In [131]:
x[np.where(x == "Loro")]

array(['Loro', 'Loro'], dtype='<U5')

In [134]:
filtro = np.where(x == "Loro", x, "")

array(['Loro', '', '', 'Loro', ''], dtype='<U5')

## Ejercicio 9
Crea una secuencia de 20 elementos y transformala en un array compuesto por 2 matrices de 5x2

In [136]:
ej_9 = np.arange(20).reshape(2, 5, 2)
print(ej_9)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]


## Ejercicio 10
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])
```

In [138]:
ej_4[::-1, ::-1]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

## Ejercicio 11
Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [142]:
ej_11 = np.zeros(10)
print(ej_11)
print(ej_11.nbytes)
ej_11[3] = 1
print(ej_11)
print(ej_11.nbytes)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
80
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
80


In [151]:
ej_11.dtype

dtype('float64')

In [150]:
np.full(10, 0).dtype

dtype('int32')

In [149]:
np.full(10, 1).dtype

dtype('int32')

## Ejercicio 12
Crea un vector que vaya del 10 al 49

Inviértelo

In [143]:
ej_12 = np.arange(10, 50)
print(ej_12)
print(ej_12[::-1])

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [144]:
np.flip(ej_12)

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

## Ejercicio 13
Encuentra los indices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [0, 1, 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/) Encapsúlalo en una función, con un argumento de entrada de un vector.

In [162]:
ej_13 = np.array([1,2,0,0,4,0])

In [166]:
np.where(ej_13 != 0)[0]

array([0, 1, 4], dtype=int64)

In [167]:
np.nonzero(ej_13)

(array([0, 1, 4], dtype=int64),)

In [170]:
def non_zero_val(array_to_search: list):
    array_to_search = np.array(array_to_search)
    zero_index = np.where(array_to_search != 0)[0]
    return zero_index

In [172]:
type(ej_13)

numpy.ndarray

In [169]:
non_zero_val(ej_13)

array([0, 1, 4], dtype=int64)

## Ejercicio 14
Crea una matriz de numeros aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [173]:
ej_14 = np.random.randint(1, 101, (10, 10))
print(ej_14)

[[45 11  9 39 54 83 92  8  7 85]
 [26 78 36  4 14 14 82 82 90 63]
 [42 23 86 77 16 18 77 20 23 41]
 [39 19 90 79 46 55 21 84  1 24]
 [70 48 53 49 72 51 92 30 62 38]
 [96 26 56 64 16 21 81 74 91 53]
 [83 20 31 66 23 30 30 66 29 48]
 [42 82 91  8 37 66 12 96 42 14]
 [49 18 78 31  9 66 90 20  5 66]
 [35 52 18 79 52 96 10 64  5 47]]


In [174]:
print(np.min(ej_14))
print(np.max(ej_14))

1
96


## Ejercicio 15
Crea un vector aleatorio de tamaño 30 y calcula su media

In [176]:
ej_15 = np.random.randint(1, 31, 30)
print(np.mean(ej_15))

16.9


## Ejercicio 16
Crea un array cuadrado de 2D, con las dimensiones que quieras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [179]:
ej_16 = np.ones((5, 5))
print(ej_16)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [180]:
ej_16[1:-1, 1:-1] = 0
print(ej_16)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [192]:
ej_16 = np.zeros((5, 5))
print(ej_16)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [187]:
ej_16[1:-1, 1:-1] = 0
print(ej_16)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [193]:
ej_16[::len(ej_16)-1, ::] = 1
print(ej_16)
print('\n')
ej_16[::, ::len(ej_16)-1] = 1
print(ej_16)

[[1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]]


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## Ejercicio 17
Crea una mtriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [199]:
#Partiendo de '1s'
ej_17 = np.ones((8, 8))
print(ej_17)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


In [200]:
ej_17[1::2, 1::2] = 0
print(ej_17)
print('\n')
ej_17[::2, ::2] = 0
print(ej_17)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [ ]:
#Partiendo de '0s'

In [204]:
ej_17 = np.zeros((10, 10))
print(ej_17)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [205]:
ej_17[::2, 1::2] = 1
print(ej_17)
print('\n')
ej_17[1::2, ::2] = 1
print(ej_17)

[[0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


[[0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]]


In [206]:
#Con bucles
ej_17 = np.zeros((8, 8))
print(ej_17)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [207]:
for i in range(len(ej_17)):
    for j in range(len(ej_17)):
        if (i %2 != 0 and j %2 == 0) or (i %2 == 0 and j %2 != 0):
            ej_17[i, j] = 1

print(ej_17)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


## Ejercicio 18
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [209]:
ej_18 = np.tile([[0, 1], [1, 0]], (4, 4))
print(ej_18)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [211]:
print(np.array([[0, 1], [1, 0]]))

[[0 1]
 [1 0]]


## Ejercicio 19
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [212]:
ej_19 = np.random.randint(1, 26, (5, 5))
print(ej_19)

[[17  1  6 24 12]
 [23 21 14 13 23]
 [15  9 22  7 17]
 [24 10 18 23  9]
 [10 20 24  8 25]]


In [215]:
np.std((ej_19 - np.mean(ej_19)) / np.std(ej_19))

1.0

In [216]:
np.mean((ej_19 - np.mean(ej_19)) / np.std(ej_19))

-1.1546319456101628e-16

## Ejercicio 20
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1, todos los elementos cuyo valor se encuentre entre el 3 y el 8.
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [217]:
ej_20 = np.arange(0, 11)
print(ej_20)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [218]:
ej_20_1 = ej_20.copy()
ej_20_1[(ej_20_1 > 3) & (ej_20_1 < 8)] = -1
print(ej_20_1)

[ 0  1  2  3 -1 -1 -1 -1  8  9 10]


In [221]:
ej_20_2 = ej_20.copy()
ej_20_2[(ej_20_2 > 3) & (ej_20_2 < 8)] = False
print(ej_20_2)

[ 0  1  2  3  0  0  0  0  8  9 10]
